<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="epagedev" name="com.testprice.TestPriceComfort" tests="33" failures="2" timestamp="13 Jun 2019 01:06:11 GMT" time="90.090" errors="0">
  <testcase name="test001" time="0.965" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.765" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="1.048" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.984" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.977" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.983" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="30.578" classname="com.testprice.TestPriceComfort">
    <failure type="java.lang.AssertionError" message="expected [.0] but found [29990.0]">
      <![CDATA[java.lang.AssertionError: expected [.0] but found [29990.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testprice.TestPriceComfort.test001(TestPriceComfort.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test001 -->
  <testcase name="test001" time="0.794" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="1.018" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.838" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="1.039" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.893" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="1.047" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.912" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.896" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.884" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="1.168" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.988" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.816" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.942" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="30.058" classname="com.testprice.TestPriceComfort">
    <failure type="java.lang.AssertionError" message="expected [.0] but found [29990.0]">
      <![CDATA[java.lang.AssertionError: expected [.0] but found [29990.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testprice.TestPriceComfort.test001(TestPriceComfort.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test001 -->
  <testcase name="test001" time="1.073" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="1.085" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="1.089" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.995" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.866" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.896" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.721" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.988" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.980" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.865" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="1.005" classname="com.testprice.TestPriceComfort"/>
  <testcase name="test001" time="0.934" classname="com.testprice.TestPriceComfort"/>
</testsuite> <!-- com.testprice.TestPriceComfort -->
